version: '3'

services:

  census_etl-server:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=psql://postgres:root@db-dev:5432/python-dev
    depends_on:
      - db-dev
    networks:
      - db-network

  db-dev:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "python-dev"
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - db-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "bbereoff@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "16543:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db-dev
    networks:
      - db-network

networks:
  db-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin-data:
